/*----------------------------------------------------------------------------
	Program : getYAHOO.c
	Author  : Tom Stevelt
	Date    : Jan 2024
	Synopsis:Load history from csv file generated by YAHOO_FIN (not YFINANCE)
	Return  : 

	Who		Date		Modification
	---------------------------------------------------------------------
	tms		06/25/2024	Added update Shigh52 and Sdate52.

----------------------------------------------------------------------------*/
//     Invest extras
// 
//     Copyright (C)  2019 - 2024 Tom Stevelt
// 
//     This program is free software: you can redistribute it and/or modify
//     it under the terms of the GNU Affero General Public License as
//     published by the Free Software Foundation, either version 3 of the
//     License, or (at your option) any later version.
// 
//     This program is distributed in the hope that it will be useful,
//     but WITHOUT ANY WARRANTY; without even the implied warranty of
//     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//     GNU Affero General Public License for more details.
// 
//     You should have received a copy of the GNU Affero General Public License
//     along with this program.  If not, see <https://www.gnu.org/licenses/>.

#define		MAIN
#include	"getYAHOO.h"

int main ( int argc, char *argv[] )
{
	FILE	*fp;
	char	xbuffer[1024];
	char	*tokens[10];
	int		tokcnt, lineno, inserted, updated;
	double	AdjustedClose, Ratio;

	getargs ( argc, argv );

	StartMySQL ( &MySql, "invest" );
	
	if (( fp = fopen ( Filename, "r" )) == NULL )
	{
		printf ( "Cannot open %s\n", Filename );
		exit ( 1 );
	}

	/*----------------------------------------------------------
	0 1   2    3   4     5        6      7
	,open,high,low,close,adjclose,volume,ticker
	2014-01-02,71.04,71.08,70.38,70.60,59.63,1288800,RSP
	2014-01-03,70.74,70.85,70.48,70.54,59.58,538200,RSP
	2014-01-06,70.68,70.89,70.26,70.32,59.39,593200,RSP
	2014-01-07,70.56,70.87,70.49,70.74,59.75,662800,RSP
	2014-01-08,70.80,70.93,70.54,70.85,59.84,747700,RSP
	2014-01-09,71.08,71.12,70.58,70.93,59.91,739000,RSP
	2014-01-10,71.00,71.26,70.87,71.24,60.17,520300,RSP
	2014-01-13,71.14,71.25,70.11,70.22,59.31,916400,RSP
	2014-01-14,70.48,71.06,70.34,71.03,59.99,579100,RSP
	----------------------------------------------------------*/

	lineno = inserted = updated = 0;
	while ( fgets ( xbuffer, sizeof(xbuffer), fp ) != NULL )
	{
		lineno++;
		if ( strstr ( xbuffer, "open" ) != NULL )
		{
			continue;
		}

		if (( tokcnt = GetTokensD ( xbuffer, ",\n\r\t", tokens, 10 )) < 8 )
		{
			printf ( "syntax line %d\n", lineno );
			continue;
		}

		sprintf ( xhistory.xhdate, "%s", tokens[0] );
		xhistory.xhopen  = atof(tokens[1]);
		xhistory.xhhigh  = atof(tokens[2]);
		xhistory.xhlow   = atof(tokens[3]);
		xhistory.xhclose = atof(tokens[4]);
		AdjustedClose    = atof(tokens[5]);
		xhistory.xhvolume = atof(tokens[6]);
		sprintf ( xhistory.xhticker, "%s", tokens[7] );


		if ( AdjustHistory == 1 && AdjustedClose != xhistory.xhclose )
		{
			Ratio = AdjustedClose / xhistory.xhclose;

			xhistory.xhclose = xhistory.xhclose * Ratio;
			xhistory.xhopen  = xhistory.xhopen  * Ratio;
			xhistory.xhlow   = xhistory.xhlow   * Ratio;
			xhistory.xhhigh  = xhistory.xhhigh  * Ratio;

			if ( Debug )
			{
				printf ( "%s Adjusted %.3f %.2f %.2f %.2f %.2f %.2f\n",
						xhistory.xhdate, Ratio, xhistory.xhopen, xhistory.xhhigh, xhistory.xhlow, xhistory.xhclose, AdjustedClose );

			}
		}

		sprintf ( WhereClause, "Hticker = '%s' and Hdate = '%s'", xhistory.xhticker, xhistory.xhdate );

		if ( dbySelectCount ( &MySql, "history", WhereClause, LogFileName ) == 1 )
		{
			sprintf ( Statement, "update history set Hopen = %.2f, Hlow = %.2f, Hhigh = %.2f, Hclose = %.2f, Hvolume = %ld where Hticker = '%s' and Hdate = '%s'",
				xhistory.xhopen, xhistory.xhhigh, xhistory.xhlow, xhistory.xhclose, xhistory.xhvolume, xhistory.xhticker, xhistory.xhdate );

			updated++;
		}
		else
		{
			sprintf ( Statement, "insert into history ( Hticker, Hdate, Hopen, Hlow, Hhigh, Hclose, Hvolume) values ( '%s', '%s', %.2f, %.2f, %.2f, %.2f, %ld )",
				xhistory.xhticker, xhistory.xhdate, xhistory.xhopen, xhistory.xhhigh, xhistory.xhlow, xhistory.xhclose, xhistory.xhvolume );

			inserted++;
		}

		printf ( "%s;\n", Statement );
	}

	printf ( "update stock set Slast = (select max(Hdate) from history where Hticker = '%s') where Sticker = '%s';\n", xhistory.xhticker, xhistory.xhticker );


	printf ( "select max(Hdate) from history where Hticker = '%s' into @DATE;\n", xhistory.xhticker );
	printf ( "select @DATE;\n" );
	printf ( "select date_sub(@DATE,interval 1 year) into @YEARAGO;\n" );
	printf ( "select @YEARAGO ;\n" );
	printf ( "select max(Hhigh) from history where Hticker = '%s' and Hdate > @YEARAGO into @HIGH52;\n", xhistory.xhticker );
	printf ( "select @HIGH52 ;\n" );
	printf ( "select Hdate from history where Hticker = '%s' and Hdate > @YEARAGO and Hhigh = @HIGH52 into @DATE52 ;\n", xhistory.xhticker );
	printf ( "update stock set Shigh52 = @HIGH52, Sdate52 = @DATE52 where Sticker = '%s';\n", xhistory.xhticker );

	fclose ( fp );

	fprintf ( stderr, "getYAHOO inserted %d updated %d\n", inserted, updated );

	return ( 0 );
}
